### PR TITLE
RE-1329 Fix interpolation escape and move console log compression to periodic cleanup

### PR DESCRIPTION
**Pull request by hughsaunders**
These variables are bash variables not groovy variables, so the dollar
signs should escaped.

Issue: [RE-1329](https://rpc-openstack.atlassian.net/browse/RE-1329)

### CODE REVIEW

**Comment by hughsaunders** [comment]
Manually updated the job with these changes and is running ok: https://rpc.jenkins.cit.rackspace.net/job/Periodic-Cleanup/7905/console

**Comment by hughsaunders** [comment]
recheck_unit_tests

**Comment by hughsaunders** [comment]
recheck_unit_tests

**Comment by mattt416** [comment]
recheck_cit_xenial_lint_test
recheck_cit_xenial_functional_test

**Comment by mattt416** [comment]
recheck_all

**Comment by mattt416** [comment]
recheck_all

**Comment by mattt416** [comment]
@hughsaunders job results aren't being posted back to this PR for some reason -- not entirely sure what's going on here!

**Comment by hughsaunders** [comment]
recheck_unit_tests

**Comment by hughsaunders** [comment]
recheck_all

**Comment by hughsaunders** [comment]
recheck_all

**Comment by hughsaunders** [comment]
recheck_all

**Comment by hughsaunders** [comment]
recheck_all

**Comment by hughsaunders** [comment]
recheck_all

**Comment by hughsaunders** [comment]
recheck_all

**Comment by hughsaunders** [comment]
recheck_all

**Comment by hughsaunders** [comment]
recheck_issue_link

**Comment by hughsaunders** [comment]
recheck_unit_tests

**Comment by hughsaunders** [comment]
recheck_issue_link

**Comment by hughsaunders** [comment]
recheck_issue_link

**Pull request merged**
