### PR TITLE
[RI-475] add a constraints update job

### PR DESCRIPTION
**Pull request by prometheanfire**
Issue: [RI-475](https://rpc-openstack.atlassian.net/browse/RI-475)

### CODE REVIEW

**Comment by prometheanfire** [comment]
not sure what I need to call the tox job to update constraints...

**Comment by prometheanfire** [comment]
:-1:

**Comment by prometheanfire** [comment]
no reason other than not wanting to 'pollute' a sha update job

**Comment by odyssey4me** [comment]
> no reason other than not wanting to 'pollute' a sha update job

The purpose of the dependency update jobs is to update internal and external dependencies. This seems to fit that purpose. If a different job is preferred, that's OK, but it will be outside the norm which will cause confusion.

**Comment by prometheanfire** [comment]
that's fine, will be easier to add it there anyway :D

**Comment by prometheanfire** [comment]
should I close this in favour of https://github.com/rcbops/rpc-openstack/pull/3313 ?

**Comment by odyssey4me** [comment]
Closed in favor of https://github.com/rcbops/rpc-openstack/pull/3313

**Pull request closed without merging**
