### PR TITLE
RE-1788 Add rpc-upgrades release jobs

### PR DESCRIPTION
**Pull request by mattt416**
This commit adds some rpc-upgrades release jobs, and fine-tunes
skip_pattern for PR jobs.

Issue: [RE-1788](https://rpc-openstack.atlassian.net/browse/RE-1788)

### CODE REVIEW

**Comment by mattt416** [comment]
Hey @antonym @rexredinger, I basically duplicated your functional PR jobs as RELEASE jobs -- the jobs that will get run before a release is cut. Can you confirm if you're happy with this -- or if you'd rather just run a single job, an MNAIO job, or anything else that makes sense for rpc-upgrades?

**Comment by mattt416** [comment]
@antonym @rexredinger Actually, should I exclude kilo_to_newton_leap since that's not a required PR job ?

**Comment by antonym** [comment]
Yeah, I'd drop the Kilo job... the bits are so old it breaks pretty often, thanks!

**Comment by mattt416** [comment]
@antonym sounds good -- fixed !

**Pull request merged**
