### PR TITLE
Change job scenario names for MaaS snapshot jobs

### PR DESCRIPTION
**Pull request by xeregin**

### CODE REVIEW

**Comment by jlpogue3** [comment]
recheck_xenial_lint_test

**Comment by hughsaunders** [comment]
These jobs will need to be modified so that their full names are less than 77 chars. 

```
00:08:58.266 ** Scanning for job names for those that are longer than 77 characters ... **
00:08:58.266 81	PM_rpc-maas-master-rpc-r14-trusty_loose_artifacts-swift-newton-trusty-snap-deploy
00:08:58.266 81	PM_rpc-maas-master-rpc-r14-xenial_loose_artifacts-swift-newton-xenial-snap-deploy
00:08:58.266 79	PM_rpc-maas-master-rpc-r16-xenial_loose_artifacts-swift-pike-xenial-snap-deploy
00:08:58.266 81	PM_rpc-maas-master-rpc-r17-xenial_loose_artifacts-swift-queens-xenial-snap-deploy
00:08:58.266 80	PM_rpc-maas-master-rpc-r18-bionic_loose_artifacts-swift-rocky-bionic-snap-deploy
00:08:58.266 80	PM_rpc-maas-master-rpc-r18-xenial_loose_artifacts-swift-rocky-xenial-snap-deploy
00:08:58.266 ** 6 problematic job name(s) found! **
```

This is to do with the kernel shebang line length maximum of 127 chars, when executing python scripts from a venv.

**Comment by jlpogue3** [comment]
turns out it's a real limit of 77 char based on virtualenv path length limits (https://github.com/rcbops/rpc-gating/blob/07bdc80bcb72a5b24dbfa6ad2afd602fda43e0cc/lint.sh#L171-L181).

The problematic job names are

81	PM_rpc-maas-master-rpc-r14-trusty_loose_artifacts-swift-newton-trusty-snap-deploy
81	PM_rpc-maas-master-rpc-r14-xenial_loose_artifacts-swift-newton-xenial-snap-deploy
79	PM_rpc-maas-master-rpc-r16-xenial_loose_artifacts-swift-pike-xenial-snap-deploy
81	PM_rpc-maas-master-rpc-r17-xenial_loose_artifacts-swift-queens-xenial-snap-deploy
80	PM_rpc-maas-master-rpc-r18-bionic_loose_artifacts-swift-rocky-bionic-snap-deploy
80	PM_rpc-maas-master-rpc-r18-xenial_loose_artifacts-swift-rocky-xenial-snap-deploy

Perhaps remove the repeated reference to the ubuntu name, i.e. xenial/bionic/trusty ?

**Comment by odyssey4me** [comment]
I dunno what all the parts of the name are used for, but there is repetition and quite a few unnecessary words: Eg: For ``trusty_loose_artifacts-swift-newton-trusty-snap-deploy`` the word ``trusty`` is used twice and the string ``_loose_artifacts-`` is in every single job name.

**Comment by dealako** [comment]
recheck_unit_tests

**Comment by xeregin** [comment]
recheck_unit_tests

**Comment by hughsaunders** [comment]
This PR requires an associated change to the MaaS repo because scenario names are changed: https://github.com/rcbops/rpc-maas/pull/618/files

**Comment by odyssey4me** [comment]
The PR @hughsaunders has referred to has a merge conflict which needs resolving before we can continue.

**Comment by shannonmitchell** [comment]
moved to github actions

**Pull request closed without merging**
