### PR TITLE
RE-1335 Remove ops_fabric_chatbot.yml

### PR DESCRIPTION
**Pull request by mattt416**
These jobs are being moved over to Ops Fabric's CI infrastructure, so
once we get confirmation from the team these can be removed.

Issue: [RE-1335](https://rpc-openstack.atlassian.net/browse/RE-1335)

### CODE REVIEW

**Comment by mattt416** [comment]
Hold off on merging/testing this one for the time being.  This project is no longer using CIT Jenkins, so waiting no @hmakkapati, @jedsmith, or @supermari0 to confirm that we're free to delete the existing job.

**Comment by hmakkapati** [comment]
@mattt416 We are not using this job any more to gate `ops-fabric-analytics` repo. We have a separate set of gates set up on a different Jenkins host. So, `ops-fabric-analytics` jobs on cit jenkins can be safely removed.
Although `ops-fabric-chatbot` repo currently seems to be running gate jobs on cit, we are planning to move them soon as well. Let me confirm in a few mins whether the chatbot jobs can be deleted as well.

**Comment by hmakkapati** [comment]
@mattt416 So, I'll move the chatbot job over to the other Jenkins instance we are using. Once I do that, I'll notify you.

**Comment by mattt416** [comment]
👍 @hmakkapati

**Comment by git-harry** [comment]
@hmakkapati have you made any progress with this or do you have an issue logged that we can track?

**Comment by hmakkapati** [comment]
@mattt416 So, we finally moved Chatbot gating to our own Jenkins instance. It is now safe to drop this job.

**Pull request merged**
