### PR TITLE
RE-1735 VPN Playbook Fails with Undefined Vars

### PR DESCRIPTION
**Pull request by dealako**
- Wrapped phobos_vpn.yml with appropriate VPN variables

JIRA: RE-1735

Issue: [RE-1735](https://rpc-openstack.atlassian.net/browse/RE-1735)

### CODE REVIEW

**Comment by dealako** [comment]
@odyssey4me - Amended to include changes to `playbooks/phobos_vpn.yml` that were part of this commit package.

**Comment by odyssey4me** [comment]
@dealako LGTM - Could you do a JJB job rebuild for this job, then test running it to confirm that it works?

**Comment by dealako** [comment]
@odyssey4me here's the link buddy: https://rpc.jenkins.cit.rackspace.net/job/Jenkins-Job-Builder/1062/console

**Comment by dealako** [comment]
Looks like everything passes as well: https://rpc.jenkins.cit.rackspace.net/job/Jenkins-Job-Builder/1063/console

**Comment by dealako** [comment]
@odyssey4me how about now? https://rpc.jenkins.cit.rackspace.net/job/Setup-Nodepool/450/console

**Pull request merged**
