### PR TITLE
RE-1169 Add SLAVE_TYPE="dockerfile"

### PR DESCRIPTION
**Pull request by mattt416**
This adds a new SLAVE_TYPE of `dockerfile` to allow a project to use
their own Dockerfile.

Issue: [RE-1169](https://rpc-openstack.atlassian.net/browse/RE-1169)

### CODE REVIEW

**Comment by hughsaunders** [comment]
If we go ahead with this approach we should merge #633 first, then add a unit test with for an external dockerfile.

**Comment by mattt416** [comment]
Tested [here](https://rpc.jenkins.cit.rackspace.net/job/PM_ops-fabric-analytics-master-container-unit-test/2/console), you can see in-repo Dockerfile (and non-standard base image) being used.

**Comment by mattt416** [comment]
TODO: Add a test for this after #633 merges.

**Comment by mattt416** [comment]
recheck_cit_unit_tests

**Comment by hughsaunders** [comment]
@mattt416 Would is be possible to add dockerfile as an optional param to the container type, similar to SLAVE_CONTAINER_BASE_IMAGE in #627 ?

**Comment by mattt416** [comment]
recheck_cit_unit_tests

**Comment by mattt416** [comment]
recheck_cit_xenial_functional_test
recheck_cit_xenial_lint_test

**Comment by mattt416** [comment]
recheck_cit_unit_tests

**Comment by mattt416** [comment]
Closing in favour of https://github.com/rcbops/rpc-gating/pull/645.

**Pull request closed without merging**
