### PR TITLE
Drop AIO jobs in favor of MNAIO snaps

### PR DESCRIPTION
**Pull request by antonym**
Drops a number of AIO/MNAIO jobs to start switching to
using MNAIO snaps and adds some incremental
jobs.

### CODE REVIEW

**Comment by antonym** [comment]
recheck_xenial_lint_test

**Comment by antonym** [comment]
It runs some basic validation release jobs but they are more testing to validate things are working than spitting out artifacts.

**Comment by antonym** [comment]
Compressed it a bit further and removed release from the name which isn't the release.

**Comment by odyssey4me** [comment]
FYI the term `snapshot` refers to AIO snapshots, whereas the MNAIO tooling refers to `images`. It may be good to use the appropriate terminology for the job names and scripts to prevent confusion.

**Pull request merged**
