### PR TITLE
Standardize name format

### PR DESCRIPTION
**Pull request by mkam**
The jobs that had named changes are:

- 'OnMetal_Multi_Node_AIO_Merge_Trigger_{series}' ->  'OnMetal-Multi-Node-AIO-Merge-Trigger_{series}'
- 'OnMetal-Multi-Node-AIO_{series}-{context}-{trigger}' ->  'OnMetal-Multi-Node-AIO_{series}-{context}-{trigger}'
- 'RPC-Artifact_Build-{series}-{image}-{context}-{ztrigger}' -> 'RPC-Artifact-Build_{series}-{image}-{context}-{ztrigger}'
- 'rpc-gating-lint' -> name: 'RPC-Gating-Lint'
- Single_Use_Slave_Example -> Single-Use-Slave-Example

If we want to preserve the history on those jobs, we might have to rename them so that the old jobs aren't deleted.

Connects https://github.com/rcbops/u-suk-dev/issues/1452

### CODE REVIEW

**Comment by git-harry** [comment]
It would be nice to add some tests here.

**Comment by mkam** [comment]
recheck_lint

**Comment by mkam** [comment]
I went ahead and renamed the jobs, and I'll open a separate card for adding tests just so we can start using the new names now.

**Comment by mattt416** [comment]
👍

**Pull request merged**
