### PR TITLE
RE-703 Merge rpc_gating_lint with pre_merge_test

### PR DESCRIPTION
**Pull request by git-harry**
`rpc_gating_lint.yml` is a pre-merge job used by rpc-gating to run
`lint.sh`. This change removes `rpc_gating_lint.yml` and adds lint to
the list of scenarios covered by the rpc-gating pre-merge project.

Separate scripts for functional and lint tests have been created in
`gating/common/`. `gating/pre_merge_test/run` and
`gating/post_merge_test/run` have been updated to run the appropriate
script based on the scenario name, this reduces duplication and makes
them work in a consistent manner.

The comment in `gating/post_merge_test/run` was removed (not copied to
`gating/common/run_lint.sh`) because it appeared to be referencing the
implementation in `rpc_gating_lint.yml` which is removed by this change.

Issue: [RE-703](https://rpc-openstack.atlassian.net/browse/RE-703)

### CODE REVIEW

**Comment by mattt416** [comment]
Do we want to change the action name in `rpc_jobs/standard_job_premerge.yml` to reflect that this is now a lint test?

**Comment by git-harry** [comment]
@mattt416 you make a good point regarding the naming, on looking again it probably doesn't make sense to combine them. I've updates the commit with the changes shown below to add an additional scenario.

```diff
diff --git a/gating/common/run_functional.sh b/gating/common/run_functional.sh
new file mode 100755
index 0000000..610adf8
--- /dev/null
+++ b/gating/common/run_functional.sh
@@ -0,0 +1,16 @@
+#!/bin/bash -xeu
+
+mkdir -p ${RE_HOOK_ARTIFACT_DIR}
+
+# Record the datetime as a basic artifact
+date > ${RE_HOOK_ARTIFACT_DIR}/datestamp
+
+# Record the job parameters as an artifact
+cat <<EOF > ${RE_HOOK_ARTIFACT_DIR}/environment
+RE_JOB_NAME: ${RE_JOB_NAME}
+RE_JOB_IMAGE: ${RE_JOB_IMAGE}
+RE_JOB_SCENARIO: ${RE_JOB_SCENARIO}
+RE_JOB_ACTION: ${RE_JOB_ACTION}
+RE_JOB_FLAVOR: ${RE_JOB_FLAVOR}
+RE_JOB_TRIGGER: ${RE_JOB_TRIGGER}
+EOF
diff --git a/gating/post_merge_test/run b/gating/post_merge_test/run
index c9f7619..9d2cc64 100755
--- a/gating/post_merge_test/run
+++ b/gating/post_merge_test/run
@@ -1,3 +1,3 @@
 #!/bin/bash -xeu
 
-gating/common/run_lint.sh
+gating/common/run_${RE_JOB_SCENARIO}.sh
diff --git a/gating/pre_merge_test/run b/gating/pre_merge_test/run
index eab7730..9d2cc64 100755
--- a/gating/pre_merge_test/run
+++ b/gating/pre_merge_test/run
@@ -1,17 +1,3 @@
 #!/bin/bash -xeu
-mkdir -p ${RE_HOOK_ARTIFACT_DIR}
 
-# Record the datetime as a basic artifact
-date > ${RE_HOOK_ARTIFACT_DIR}/datestamp
-
-# Record the job parameters as an artifact
-cat <<EOF > ${RE_HOOK_ARTIFACT_DIR}/environment
-RE_JOB_NAME: ${RE_JOB_NAME}
-RE_JOB_IMAGE: ${RE_JOB_IMAGE}
-RE_JOB_SCENARIO: ${RE_JOB_SCENARIO}
-RE_JOB_ACTION: ${RE_JOB_ACTION}
-RE_JOB_FLAVOR: ${RE_JOB_FLAVOR}
-RE_JOB_TRIGGER: ${RE_JOB_TRIGGER}
-EOF
-
-gating/common/run_lint.sh
+gating/common/run_${RE_JOB_SCENARIO}.sh
diff --git a/rpc_jobs/standard_job_premerge.yml b/rpc_jobs/standard_job_premerge.yml
index e1fc8a3..c0503fd 100644
--- a/rpc_jobs/standard_job_premerge.yml
+++ b/rpc_jobs/standard_job_premerge.yml
@@ -12,6 +12,7 @@
       - "xenial"
     scenario:
       - "functional"
+      - "lint"
     action:
       - "test"
     jobs:
```

**Comment by mattt416** [comment]
Agree w/ @hughsaunders here.  I don't think that functional test gives us anything when we're doing the lint test that essentially tests the same plumbing.

**Comment by git-harry** [comment]
@hughsaunders @mattt416 `run_functional.sh` is explicitly testing two components of rpc-gating that are not tested by `lint.sh` and can't really be called lint. They are artefact archival and hook environment variables, although where the environment variables are concerned I'm not sure this was intentional and it's only half implemented.

**Pull request merged**
